insert into [Banks] ([name], [code]) values
(N'Ngân hàng Chính sách xã hội', 'NHCSXH/VBSP'),
(N'Ngân hàng Phát triển Việt Nam', 'VDB'),
(N'Ngân hàng Nông nghiệp và Phát triển Nông thôn VN', 'Agribank'),
(N'Ngân hàng Xây dựng', 'CB'),
(N'Ngân hàng Đại Dương', 'Oceanbank'),
(N'Ngân hàng Dầu Khí Toàn Cầu', 'GPBank'),
(N'Đầu tư và Phát triển Việt Nam', 'BIDV, BID'),
(N'Công Thương Việt Nam', 'VietinBank, CTG'),
(N'Ngoại thương Việt Nam', 'Vietcombank, VCB'),
(N'Việt Nam Thịnh Vượng', 'VPBank, VPB'),
(N'Quân đội', 'MB, MBB'),
(N'Kỹ Thương Việt Nam', 'Techcombank, TCB'),
(N'Ngân hàng Á Châu', 'ACB'),
(N'Sài Gòn-Hà Nội', 'SHB'),
(N'NH TMCP Phát triển Nhà Tp HCM', 'HDBank, HDB'),
(N'Ngân hàng TMCP Sài Gòn', 'SCB'),
(N'Sài Gòn Thương Tín', 'Sacombank, STB'),
(N'Ngân hàng Tiên Phong', 'TPBank, TPB'),
(N'NH TMCP Quốc tế Việt Nam', 'VIB'),
(N'Hàng Hải Việt Nam', 'MSB'),
(N'Ngân hàng Đông Nam Á', 'SeABank, SSB'),
(N'Phương Đông', 'OCB'),
(N'Ngân hàng xuất nhập khẩu Việt Nam', 'Eximbank, EIB'),
(N'Bưu điện Liên Việt', 'LPbank, LPB'),
(N'Đại chúng Việt Nam', 'PVcombank'),
(N'Ngân hàng TMCP Bắc Á', 'Bac A Bank, BAB'),
(N'Ngân hàng An Bình', 'ABBANK, ABB'),
(N'Ngân hàng TMCP Đông Á', 'Đông Á Bank'),
(N'Bảo Việt', 'BaoViet Bank'),
(N'Ngân hàng TMCP Nam Á', 'Nam A Bank, NAB'),
(N'Việt Nam Thương Tín', 'VietBank, VBB'),
(N'Ngân hàng TMCP Việt Á', 'Viet A Bank, VAB'),
(N'Quốc Dân', 'NCB'),
(N'Ngân hàng Bản Việt', 'BVBank, BVB'),
(N'Kiên Long', 'Kienlongbank, KLB'),
(N'Sài Gòn Công Thương', 'Saigonbank, SGB'),
(N'Xăng dầu Petrolimex', 'PG Bank, PGB'),
(N'Ngân hàng TNHH MTV Shinhan Việt Nam', 'Shinhan Bank'),
(N'Ngân hàng TNHH một thành viên HSBC Việt Nam', 'HSBC'),
(N'Ngân hàng Standard Chartered', 'Standard Chartered'),
(N'Ngân hàng Woori Bank tại Việt Nam', 'Woori Bank'),
(N'Ngân hàng CIMB tại Việt Nam', 'CIMB Bank'),
(N'Ngân hàng Public Bank Việt Nam', 'Public Bank'),
(N'Ngân hàng Hong Leong Việt Nam', 'Hong Leong Bank'),
(N'Ngân hàng UOB tại Việt Nam', 'UOB'),
(N'Ngân hàng TNHH một thành viên ANZ Việt Nam', 'ANZ'),
(N'Ngân hàng Citibank Việt Nam', null),
(N'Ngân hàng Deutsche Bank Việt Nam', null),
(N'Ngân hàng Đầu tư và Phát triển Campuchia', null),
(N'Ngân hàng Mizuho', null),
(N'Ngân hàng MUFG Bank', null),
(N'Ngân hàng Sumitomo Mitsui Banking Corporation', null),
(N'Ngân hàng Commonwealth Bank tại Việt Nam', null),
(N'Ngân hàng Bank of China tại Việt Nam', null),
(N'Ngân hàng Maybank tại Việt Nam', null),
(N'Ngân hàng ICBC tại Việt Nam', null),
(N'Ngân hàng Scotiabank tại Việt Nam', null),
(N'Ngân hàng Commercial Siam bank tại Việt Nam', null),
(N'Ngân hàng BNP Paribas tại Việt Nam', null),
(N'Ngân hàng Bankok bank tại Việt Nam', null),
(N'Ngân hàng WB tại Việt Nam', null),
(N'Ngân hàng RHB (Malaysia) tại Việt Nam', null),
(N'Ngân hàng Intesa Sanpaolo (Italia) tại Việt Nam', null),
(N'Ngân hàng JP Morgan Chase Bank (Mỹ) tại Việt Nam', null),
(N'Ngân hàng Wells Fargo (Mỹ) tại Việt Nam', null),
(N'Ngân hàng BHF - Bank Aktiengesellschaft (Đức) tại Việt Nam', null),
(N'Ngân hàng Unicredit Bank AG (Đức) tại Việt Nam', null),
(N'Ngân hàng Landesbank Baden-Wuerttemberg (Đức) tại Việt Nam', null),
(N'Ngân hàng Commerzbank AG (Đức) tại Việt Nam', null),
(N'Ngân hàng Bank Sinopac (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Chinatrust Commercial Bank (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Union Bank of Taiwan (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Hua Nan Commercial Bank, Ltd (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Cathay United Bank (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Taishin International Bank (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Land Bank of Taiwan (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng The Shanghai Commercial and Savings Bank, Ltd (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Taiwan Shin Kong Commercial Bank (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng E.Sun Commercial Bank (Đài Loan) tại Việt Nam', null),
(N'Ngân hàng Natixis Banque BFCE (Pháp) tại Việt Nam', null),
(N'Ngân hàng Société Générale Bank - tại TP. HCM (Pháp) tại Việt Nam', null),
(N'Ngân hàng Fortis Bank (Bỉ) tại Việt Nam', null),
(N'Ngân hàng RBI (Áo) tại Việt Nam', null),
(N'Ngân hàng Phongsavanh (Lào) tại Việt Nam', null),
(N'Ngân hàng Acom Co., Ltd (Nhật) tại Việt Nam', null),
(N'Ngân hàng Mitsubishi UFJ Lease & Finance Company Limited (Nhật) tại Việt Nam', null),
(N'Ngân hàng Industrial Bank of Korea (Hàn Quốc) tại Việt Nam', null),
(N'Ngân hàng KEB Hana (Hàn Quốc) tại Việt Nam', null),
(N'Ngân hàng Kookmin Bank (Hàn Quốc) tại Việt Nam', null),
(N'Ngân hàng Bank of India (Ấn Độ) tại Việt Nam', null),
(N'Ngân hàng Indian Oversea Bank (Ấn Độ) tại Việt Nam', null),
(N'Ngân hàng Rothschild Limited (Singapore) tại Việt Nam', null),
(N'Ngân hàng The Export-Import Bank of Korea (Hàn Quốc) tại Việt Nam', null),
(N'Ngân hàng Busan - (Hàn Quốc) tại Việt Nam', null),
(N'Ngân hàng Ogaki Kyorítu (Nhật Bản) tại Việt Nam', null),
(N'Ngân hàng Phát triển Hàn Quốc (Hàn Quốc) tại Việt Nam', null),
(N'Ngân hàng Phát triển châu Á (ADB) tại Việt Nam', null),
(N'Ngân hàng BPCE', null),
(N'Ngân hàng Oversea-Chinese Banking Corp (OCBC) tại Việt Nam', null),
(N'Ngân hàng Kbank Việt Nam', null)
